server:
  port: 8761
spring:
  application:
    name: lagou-cloud-eureka-server # 应用名称，会在Eureka中作为服务名称

#eureka客户端配置(和Server交互)，EurekaServer 其实也是一个Client
eureka:
  instance:
    hostname: localhost # 当前Eureka实例的主机名

  client:
    service-url: #配置客户端所交互的Eureka Server的地址 地址指向自己地址
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka  #http://localhost:8761/eureka

    register-with-eureka: false  # 当前自己就是Server，不需要注册自己
    fetch-registry: false # 查询获取注册中的服务信息，自己就是Server，不需要冲Eureka Server中获取信息

















