server:
  port: 8081
spring:
  application:
    name: lagou-service-resume

  zipkin:
    base-url: http://localhost:9411 # zipkin server的请求地址
    sender:
      # web 客户端将踪迹⽇志数据通过⽹络请求的⽅式传送到服务端，另外还有配置
      # kafka/rabbit 客户端将踪迹⽇志数据传递到mq进⾏中转
      type: web #直接向这个地址发送请求
  sleuth:
    sampler:
      # 采样率 1 代表100%全部采集 ，默认0.1 代表10% 的请求踪迹数据会被采集
      # ⽣产环境下，请求量⾮常⼤，没有必要所有请求的踪迹数据都采集分析，对于⽹络包括server端压⼒都是⽐较⼤的，
      # 可以配置采样率采集⼀定⽐例的请求的踪迹数据进⾏分析即可
      probability: 1
  datasource:
   driver-class-name: com.mysql.jdbc.Driver
   #url: jdbc:mysql://localhost:3306/lagou?useUnicode=true&characterEncoding=utf8
   url: jdbc:mysql://localhost:3306/lagou?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
   username: root
   password: root

  jpa:
   database: MySQL
   show-sql: true
   hibernate:
    naming:
     physical-strategy:
      org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl #避免将驼峰命名转换为下划线命名

# 注册到Eureka服务中心
eureka:
  client:
    service-url:
      # 注册集群，就把多个Eureka地址 使用逗号链接起来即可
      defaultZone: http://LagouCloudEurekaServerA:8761/eureka,http://LagouCloudEurekaServerB:8762/eureka
  instance:
    prefer-ip-address: true # 服务实例中显示IP，而不是显示主机名
    # ip-address: 192.168.56.1
    # 自定义实例名称
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}:1.0-SNAPSHOT

    # 自定义元数据
    metadata-map:
      cluster: cl1
      regin: shanghai

#分布式链路追踪
logging:
  level:
    org.springframework.web.servlet.DispatcherServlet: debug
    org.springframework.cloud.sleuth: debug